# Generated by Django 5.0.1 on 2024-02-06 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_id_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('des', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('isTeach', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=7)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_users', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='api.user')),
            ],
            options={
                'db_table': 'usercourse',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
